# report.py
# Assembles the final .txt report from pipeline results.

import os
from datetime import datetime

import yaml


def generate_report(
    results: dict,
    input_path: str,
    config_path: str = "config.yaml",
    output_dir_override: str = None,
) -> str:
    """
    Generate a .txt report from pipeline results and save it to the output directory.

    Args:
        results:            The dict returned by run_pipeline()
        input_path:         Path to the original input NIfTI file
        config_path:        Path to config.yaml (to read output dir)
        output_dir_override: If set, overrides the output dir from config

    Returns:
        Path to the saved report file
    """
    # Determine output directory
    if output_dir_override:
        output_dir = output_dir_override
    else:
        with open(config_path, "r") as f:
            config = yaml.safe_load(f)
        output_dir = config.get("output", {}).get("dir", "./outputs")

    os.makedirs(output_dir, exist_ok=True)

    # Build report filename from input filename + timestamp
    input_stem = os.path.basename(input_path).replace(".nii.gz", "").replace(".nii", "")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_filename = f"{input_stem}_report_{timestamp}.txt"
    report_path = os.path.join(output_dir, report_filename)

    # Build report lines
    lines = []
    lines += _header(input_path)
    lines += _section_totalsegmentator(results.get("totalsegmentator", {}))
    lines += _section_emphysema(results.get("emphysema", {}))
    lines += _section_nodule(results.get("lung_nodule", {}))
    lines += _footer()

    # Write to file
    report_text = "\n".join(lines)
    with open(report_path, "w") as f:
        f.write(report_text)

    # Also print to terminal
    print("\n" + report_text)

    return report_path


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _header(input_path: str) -> list:
    return [
        "=" * 60,
        "  THORACIC CT ANALYSIS REPORT",
        "=" * 60,
        f"  Input : {os.path.basename(input_path)}",
        f"  Date  : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "=" * 60,
        "",
    ]


def _footer() -> list:
    return [
        "",
        "=" * 60,
        "  DISCLAIMER",
        "=" * 60,
        "  This report is generated by an experimental research tool.",
        "  It is NOT a medical device and NOT intended for clinical use.",
        "  All findings must be reviewed by a qualified radiologist.",
        "=" * 60,
    ]


def _status_line(status: str) -> str:
    """Format a module status for display."""
    if status == "skipped":
        return "  Status : SKIPPED (disabled in config)"
    elif status == "failed":
        return "  Status : FAILED"
    elif status == "success":
        return "  Status : OK"
    return f"  Status : {status}"


def _section_totalsegmentator(data: dict) -> list:
    lines = [
        "-" * 60,
        "  [1] SEGMENTATION — TotalSegmentator",
        "-" * 60,
    ]

    status = data.get("status", "skipped")
    lines.append(_status_line(status))

    if status == "failed":
        lines.append(f"  Error  : {data.get('error', 'unknown error')}")
        lines.append("")
        return lines

    if status == "skipped":
        lines.append("")
        return lines

    # Volumes
    volumes = data.get("volumes_ml", {})
    lines.append("")
    lines.append("  Organ Volumes:")

    # Labels for display
    display_names = {
        "heart":               "Heart",
        "thyroid_gland":       "Thyroid gland",
        "adrenal_gland_left":  "Adrenal gland (left)",
        "adrenal_gland_right": "Adrenal gland (right)",
    }
    normal_ranges = {
        "heart":               "< 524 mL (women) / < 670 mL (men)",
        "thyroid_gland":       "< 25 mL",
        "adrenal_gland_left":  "< 10 mL",
        "adrenal_gland_right": "< 10 mL",
    }

    for key, label in display_names.items():
        vol = volumes.get(key)
        if vol is None:
            lines.append(f"    {label:<25} : not detected")
        else:
            ref = normal_ranges.get(key, "")
            lines.append(f"    {label:<25} : {vol} mL  (ref: {ref})")

    # Flagged findings
    flagged = data.get("flagged_findings", [])
    lines.append("")
    if flagged:
        lines.append("  *** FLAGGED FINDINGS ***")
        for f in flagged:
            lines.append(
                f"    ! {f['finding']}: {f['volume_ml']} mL "
                f"(threshold: {f['threshold_ml']} mL, ref: {f['normal_range']})"
            )
    else:
        lines.append("  No abnormal volumes detected.")

    # Notes (e.g. structures outside field of view)
    notes = data.get("notes", [])
    if notes:
        lines.append("")
        lines.append("  Notes:")
        for note in notes:
            lines.append(f"    - {note}")

    lines.append("")
    return lines


def _section_emphysema(data: dict) -> list:
    lines = [
        "-" * 60,
        "  [2] EMPHYSEMA QUANTIFICATION",
        "-" * 60,
    ]

    status = data.get("status", "skipped")
    lines.append(_status_line(status))

    if status == "failed":
        lines.append(f"  Error  : {data.get('error', 'unknown error')}")
    elif status == "success":
        # Placeholder — will be filled when EmphysemaRunner is implemented
        laa = data.get("laa_950_percent")
        if laa is not None:
            flag = "  *** SIGNIFICANT ***" if laa >= 10 else ""
            lines.append(f"  LAA-950 : {laa}%  (threshold: >= 10%){flag}")

    lines.append("")
    return lines


def _section_nodule(data: dict) -> list:
    lines = [
        "-" * 60,
        "  [3] LUNG NODULE DETECTION",
        "-" * 60,
    ]

    status = data.get("status", "skipped")
    lines.append(_status_line(status))

    if status == "failed":
        lines.append(f"  Error  : {data.get('error', 'unknown error')}")
    elif status == "success":
        # Placeholder — will be filled when NoduleRunner is implemented
        nodules = data.get("nodules", [])
        if not nodules:
            lines.append("  No nodules detected.")
        else:
            lines.append(f"  {len(nodules)} nodule(s) detected:")
            for i, n in enumerate(nodules, 1):
                size = n.get("size_mm", "?")
                loc = n.get("location", "?")
                density = n.get("density", "?")
                lines.append(f"    {i}. {size} mm — {loc} — {density}")

    lines.append("")
    return lines